//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salonEntities : DbContext
    {
        public salonEntities()
            : base("name=salonEntities")
        {
        }

        public salonEntities(string connectionString)
        : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<clientservice> clientservice { get; set; }
        public virtual DbSet<documentbyservice> documentbyservice { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<manufacturer> manufacturer { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productphoto> productphoto { get; set; }
        public virtual DbSet<productsale> productsale { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<servicephoto> servicephoto { get; set; }
        public virtual DbSet<tag> tag { get; set; }
    }
}
