//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.IO;

    public partial class service : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.clientservice = new HashSet<clientservice>();
            this.servicephoto = new ObservableCollection<servicephoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        [NotMapped]
        public int DurationInMinutes => DurationInSeconds / 60;
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        string _img;

        public event PropertyChangedEventHandler PropertyChanged;

        public string MainImagePath
        {
            get => Path.Combine("pack://siteoforigin:,,,/", _img ?? ""); set
            {
                _img = System.Net.WebUtility.UrlDecode(value);
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(MainImagePath)));
            }
        }
        [NotMapped]
        public string DiscountedCost => Discount.HasValue ? (Cost - Cost * ((decimal)Discount.Value / 100)).ToString("N0") : "";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientservice> clientservice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<servicephoto> servicephoto { get; set; }
    }
}
